### ISSUE TITLE
Typings not published 

### ISSUE THREAD

**Issue by theigwe** [smileidentity/smile-identity-core-js#195]
It seems the typings for this package is not published to npm.
It's causing build issues in my typescript project.
The last publishing is 10 months ago

**Comment by ayinloya** [comment]
Hi @theigwe,
Thanks for the feedback
We are currently working on releasing typescript support.
If this is urgent, you could build and use the types currently available in the main branch.

**Comment by ayinloya** [comment]
@theigwe a new version has been released.
