### ISSUE TITLE
Do you have batch API for verifying IDs?

### ISSUE THREAD

**Issue by lud4ik** [smileidentity/smile-identity-core-js#7]

**Comment by Ridhwana** [comment]
Hi @lud4ik - No not at the moment, but you can write a script to loop over your data and you can just make the call to the IDAPI submit_job function for each data point. Our server will still process one ID at the time, however, your script will allow you to run through your entire data set.

**Comment by lud4ik** [comment]
Thank you for a quick answer. Are there any limitations for number of requests per inteval of time per partner-id?

**Comment by Ridhwana** [comment]
@lud4ik HI, no there aren't.
